name: Code Coverage

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov genbadge defusedxml

    - name: Code Coverage report
      run: 
        pytest --cov-report=xml:reports/coverage/coverage.xml --cov=. test.py

    - name: Create Coverage badge
      run: 
        genbadge coverage -i - < reports/coverage/coverage.xml -o - > coverage-badge.svg

    - name: Push changes
      if: success()
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git pull
        git diff-index --quiet HEAD || git commit -m "Updated coverage report and badge"
        git push origin main:main

    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}