name: Flake8

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8_html genbadge

    - name: Run flake8 and save traces with timestamp
      run: |
        mkdir -p post_traces
        echo -e "\nFlake8 Trace  - $(date)" >> post_traces/flake8_trace.txt
        flake8 --verbose --tee --output-file post_traces/flake8_trace.txt
        > reports/flake8/flake8stats.txt
        flake8 --exit-zero --statistics --tee --output-file reports/flake8/flake8stats.txt

    - name: Push changes
      if: success()
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git pull
        git diff-index --quiet HEAD || git commit -m "Appended flake8 traces"
        git push origin main:main

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Generating flake8 badge based on reports
    - name: Create Flake8 badge
      run:
        genbadge flake8 -v -i - < reports/flake8/flake8stats.txt -o - > reports/flake8/flake8-badge.svg

    - name: Pushing Flake8 changes
      if: success()
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git pull
        git diff-index --quiet HEAD || git commit -m "Updated flake8 badge"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}