name: Pyright

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyright
        
    - name: Run pyright and save traces with timestamp
      run: |
        mkdir -p post_traces
        echo -e "\nPyright Trace - $(date)" >> post_traces/pyright_trace.txt
        pyright >> post_traces/pyright_trace.txt
    # - uses: jakebailey/pyright-action@v1

    - name: Push changes
      if: success()
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git pull
        git diff-index --quiet HEAD || git commit -m "Appended pyright traces"
        git push origin main:main
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}