name: Radon

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install radon
        
    - name: Run radon and save traces with timestamp
      run: |
        mkdir -p post_traces
        echo -e "\nRadon Trace - $(date)" >> post_traces/radon_trace.txt
        radon 'cc' *.py -a >> post_traces/radon_trace.txt

    - name: Push changes
      if: success()
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git pull
        git diff-index --quiet HEAD || git commit -m "Appended radon traces"
        git push origin main:main

    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}